application: kindleear
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "latest"
  
- name: PIL
  version: "latest"

- name: jinja2
  version: "latest"

inbound_services:
- mail

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon    

- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: handlemail.appmail
  
- url: /.*
  script: main.app
  