application: kindleear
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
#automatic_scaling:
#  min_idle_instances: 1
#  max_idle_instances: automatic  # default value
#  min_pending_latency: automatic  # default value
#  max_pending_latency: 30ms
#  max_concurrent_requests: 50

libraries:
- name: lxml
  version: "latest"
  
- name: PIL
  version: "latest"

- name: jinja2
  version: "latest"

- name: pycrypto
  version: "latest"

inbound_services:
- mail

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /static
  static_dir: static
  application_readable: true

- url: /_ah/mail/.+
  script: apps.handlemail.appmail
  
- url: /.*
  script: apps.module_front.app
  